---
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
      - neovim/neovim
    brew_packages:
      - lua
      - vim
      - luajit
      - neovim
  tasks:
    - name: Get repo
      git: repo=git@github.com:luishdez/vim-dotfiles.git dest=~/.vim accept_hostkey=true
    - name: Link .vimrc
      file: src=~/.vim/vimrc.base dest=~/.vimrc state=link
    - name: Link .vimrc.minimal
      file: src=~/.vim/vimrc.minimal dest=~/.vimrc.minimal state=link
    - name: Link .gvimrc.base
      file: src=~/.vim/gvimrc.base dest=~/.gvimrc state=link
    - name: Ensure ~/.config
      file: path=~/.config state=directory
    - name: Link ~/.config/nvim
      file: src=~/.vim  dest=~/.config/nvim state=link
    - name: Link ~/.config/nvim/init.vim
      file: src=~/.vim/vimrc.base  dest=~/.config/nvim/init.vim state=link
    - name: Setup neobundle
      command: curl -s https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | bash
    - name: Compile bundles.yml
      command: ruby compile-vimrc chdir=~/.vim
