---
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - neovim/neovim
    brew_packages:
    - lua
    - luajit
    - neovim
  tasks:
    - git: repo=ssh://git@github.com:luishdez/vim-dotfiles.git dest=~/.nvim
    - command: ln -s .nvim/vimrc.base .nvimrc
    - command: ln -s .nvim/vimrc.minimal .mvimrc.minimal
    - command: ln -s .nvim/gvimrc.base .gnvimrc
