---
- hosts: all
  roles:
  - role: osxc.packages
    cask_packages:
      - atom
      - font-inconsolata
      - font-source-code-pro
      - font-sauce-code-powerline
  tasks:
    - name: Setup plugin for atom
      command: apm install {{ item }}
      with_items:
         - atomatigit
         - trailing-spaces
         - editorconfig
         - emmet
         - pigments
         - file-icons
         - tabularize
         - language-docker
         - language-twig
         - language-diff
         - react
         - docblockr
         - autocomplete-php
         - atom-autocomplete-php
         - atom-symfony2
         - linter
         - linter-php
         - linter-phpcs
         - linter-phpmd
         - linter-js-yaml
         - linter-htmlhint
         - linter-csslint
         - linter-eslint
         - linter-docker

    - name: Setup atom config
      template: src=templates/atom/config.cson dest=~/.atom/config.cson
    - name: Setup atom init
      template: src=templates/atom/init.coffee dest=~/.atom/init.coffee
    - name: Setup atom keymap
      template: src=templates/atom/keymap.cson dest=~/.atom/keymap.cson
    - name: Setup atom styles
      template: src=templates/atom/styles.less dest=~/.atom/styles.less

    - npm: name=dockerlint global=yes
