---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    - thoughtbot/formulae
    - gapple/services
    brew_packages:
    - jenv # Multiple java versions manager
