---
- hosts: all
  vars:
    user_email: luis.munoz.hdez@gmail.com
    user_name: Luis Hdez
  tasks:
    - name: Copy global gitconfig
      template: src=templates/git/gitconfig dest=~/.gitconfig
    - name: Copy global gitignore
      template: src=templates/git/gitignore dest=~/.gitignore
