---
- hosts: all
  vars:
    user_email: luis.munoz.hdez@gmail.com
    user_name: Luis Hdez
    date_timezone: Europe/Madrid
    project_sources_path: /Volumes/work-data/sources/
  roles:
    - role: ansible-macos.homebrew
    - role: ansible-macos.settings
    - role: developer-common
    - role: developer-terminal
    - role: developer-nginx
    - role: developer-atom
    - role: developer-php
    - role: developer-nodejs
    - role: developer-web
    - role: developer-devops
    - role: developer-datascience
    - role: developer-nvim
