---
- hosts: all
  vars:
    user_email: luis.munoz.hdez@gmail.com
    user_name: Luis Hdez
    date_timezone: Europe/Madrid
    project_sources_path: /Volumes/work-data/sources/
  roles:
    - role: osxw.developer-common
    - role: osxw.developer-terminal
    - role: osxw.developer-go
    - role: osxw.developer-nginx
    - role: osxw.developer-atom
    - role: osxw.developer-php
    - role: osxw.developer-nodejs
    - role: osxw.developer-web
    - role: osxw.developer-devops
    - role: osxw.developer-datascience
    - role: osxw.developer-nvim
    - role: osxw.user
