---
- hosts: all
  vars:
    user_email: luis.munoz.hdez@gmail.com
    user_name: Luis Hdez
    date_timezone: Europe/Madrid
  roles:
  - role: osxw.developer-common
  - role: osxw.developer-terminal
  - role: osxw.developer-php
  - role: osxw.developer-atom
  - role: osxw.developer-nodejs
  - role: osxw.developer-devops
