---
- hosts: all
  roles:
  - role: osxc.packages
    brew_packages:
    - ruby
  tasks:
    - name: ensure lunchy is installed
      gem: lunchy
    - name: ensure librarian-chef is installed
      gem: name=librarian-chef
    - name: ensure chef is installed
      gem: name=chef
    - name: ensure knife-solo is installed
      gem: name=knife-solo
    - name: ensure capistrano is installed
      gem: name=capistrano
