---
default_brew_taps:
  - homebrew/php
  - homebrew/dupes
  - homebrew/versions
  - blackfireio/homebrew-blackfire
default_php_brew:
  - phpbrew
  - php-code-sniffer
  - php-cs-fixer
  - phploc
  - phpmd
  - phpcpd
  - behat
  - phpunit
  - codeception
  - icu4c
  - composer
  - blackfire-agent
  - name: php70
    options: "without-apache,with-fpm,build-from-source"
  - name: php70-redis
    options: "HEAD,build-from-source"
  - name: php70-memcached
    options: "HEAD,build-from-source"
  - name: php70-ssh2
    options: "HEAD,build-from-source"
  - name: php70-yaml
    options: "HEAD,build-from-source"
  - php70-apcu
  - php70-apcu-bc
  - php70-oauth
  - php70-amqp
  - php70-mongodb
  - php70-ssh2
  - php70-uuid
  - php70-xdebug
  - php70-v8js
  - blackfire-php70
