---
- name: Tap hombrew formulas
  homebrew_tap: name={{ item }}
  with_items: brew_taps
  when: brew_taps is defined

- name: Install the homebrew packages
  homebrew: name={{ item }} state=latest
  with_items: brew_packages

- name: Install npm packages
  npm: name={{ item }} global=yes
  with_items: npm_packages

- name: install node stable
  command: n stable

- name: Install pip packages
  pip: name={{ item }}
  with_items: pip_packages

- name: Install gem packages
  gem: name={{ item }}
  with_items: gem_packages

- name: Install the cask packages
  homebrew_cask: name={{ item }}
  with_items: cask_packages

- name: Copy php aliases
  template: src=templates/aliases/docker.sh dest=~/.zsh/aliases/docker.sh

# Privoxy /usr/local/etc/privoxy/config
# forward-socks5   /               127.0.0.1:9050 .

# vagrant plugin install vagrant-hostsupdater
# vagrant plugin install vagrant-hostmanager
## Add to playbook /etc/sudoers
# # Allow passwordless startup of Vagrant with vagrant-hostsupdater.
# Cmnd_Alias VAGRANT_HOSTS_ADD = /bin/sh -c echo "*" >> /etc/hosts
# Cmnd_Alias VAGRANT_HOSTS_REMOVE = /usr/bin/sed -i -e /*/ d /etc/hosts
# %admin ALL=(root) NOPASSWD: VAGRANT_HOSTS_ADD, VAGRANT_HOSTS_REMOVE
