---
- name: Tap hombrew formulas
  homebrew_tap: name={{ item }}
  with_items: brew_taps
  when: brew_taps is defined

- name: Install the homebrew packages
  homebrew: name={{ item }} state=latest
  with_items: brew_packages

- name: install node stable
  command: n stable

- name: Install npm packages
  npm: name={{ item }} global=yes
  with_items: npm_packages

- name: Install pip packages
  pip: name={{ item }}
  with_items: pip_packages

- name: Install gem packages
  gem: name={{ item }}
  with_items: gem_packages

- name: Install the cask packages
  homebrew_cask: name={{ item }}
  with_items: cask_packages
