---
- name: Tap hombrew formulas
  homebrew_tap: name={{ item }}
  with_items: brew_taps
  when: brew_taps is defined

- name: Install homebrew package(s) with brew options
  homebrew: name={{ item.pkg }} install_options={{ item.opts }} state={{ item.state|default("latest") }}
  with_items: "{{ brew_packages_with_opts }}"

## Initial config
- file: path=/usr/local/etc/nginx/ssl state=directory
- file: path=/usr/local/etc/nginx/geoip state=directory
- file: path=/usr/local/etc/nginx/sites-available state=directory
- file: path=/usr/local/etc/nginx/sites-enabled state=directory
- file: path=/usr/local/etc/nginx/sites-templates state=directory
- file: path=/usr/local/etc/nginx/conf.d state=directory
- file: path=/usr/local/var/log/nginx state=directory
- file: path=/usr/local/var/nginx/fastcgi state=directory
- file: path=/usr/local/var/nginx/proxy state=directory
- file: path=/usr/local/var/nginx/client_body state=directory

- name: Project sources
  file: path={{ project_sources_path }} recurse=yes state=directory group=staff

- name: Copy nginx aliases
  template: src=templates/aliases/nginx dest=~/.zsh/aliases/nginx

- name: Copy nginx conf
  template: src=templates/conf/nginx.conf dest=/usr/local/etc/nginx/nginx.conf

- name: Copy nginx geoip conf
  template: src=templates/conf/http_geoip.conf dest=/usr/local/etc/nginx/conf.d/http_geoip.conf

- name: Download GeoIP
  get_url: url=https://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz dest=/usr/local/etc/nginx/geoip/GeoIP.dat

- name: Download GeoLiteCity
  get_url: url=https://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz dest=/usr/local/etc/nginx/geoip/GeoLiteCity.dat

- name: Copy nginx vhosts templates
  template: src=templates/{{ item }} dest=/usr/local/etc/nginx/sites-templates/{{ item }}
  with_items:
    - php-ssl.conf
    - php-symfony-ssl.conf
    - php-wordpress-ssl.conf

- file: path={{ project_sources_path }} state=directory group=staff recurse=no
