---
default_npm_packages:
  - n
  - letsencrypt-cli
default_brew_packages:
  - python
  - certbot
  - dehydrated
  - ruby
  - docker
  - s3cmd
  - libmaxminddb
  - tor
  - privoxy
  - docker-machine
default_gem_packages:
  - librarian-chef
  - knife-solo
  - capistrano
default_pip_packages:
  - awscli
  - docker-compose
default_cask_packages:
  - virtualbox
  - vagrant
