---
brew_taps: []
brew_packages:
  - n
brew_packages_with_opt:
  - pkg: jmeter
    opts: with-plugins
gem_packages:
  - sass
# cask_packages:
#   - screaming-frog-seo-spider
npm_packages:
  - less
  - gulp
  - grunt
  - grunt-cli
  - uglify-js
  - bower
  - yo
  - mversion
  - psi
  - jscs
  - eslint
