- name: Setup hg VCS
  template: src=templates/hg/hgrc dest=~/.hgrc
- name: Copy global gitconfig
  template: src=templates/git/gitconfig dest=~/.gitconfig
- name: Copy global gitignore
  template: src=templates/git/gitignore dest=~/.gitignore
- name: Copy git aliases
  template: src=templates/aliases/git.sh dest=~/.zsh/aliases/git.sh
