---
default_brew_taps:
  - gapple/services
  - caskroom/fonts
default_brew_packages:
  - git
  - git-flow
  - mercurial
  - ctags
  - wget
  - httpie
  - mongodb
  - mysql
  - redis
  - letsencrypt
default_cask_packages:
  - google-chrome
  - firefox
  - transmission
  - vlc
  - skype
  - slack
  - discord
  - sourcetree
  - sequel-pro
  - studio-3t
  - cyberduck
  - rdm
  - font-hasklig
  - font-source-code-pro
