---
brew_taps:
  - homebrew/php
  - homebrew/dupes
  - homebrew/versions
  - blackfireio/homebrew-blackfire

php_brew:
  - phpbrew
  - php-code-sniffer
  - php-cs-fixer
  - phploc
  - phpmd
  - phpcpd
  - behat
  - phpunit
  - codeception
  - icu4c
  - composer
  - blackfire-agent

## Defaults for php56
php56_brew_with_opts:
  - pkg: php56
    opts: "enable-maintainer-zts,build-from-source"
  - pkg: php56-igbinary
    opts: "build-from-source"
  - pkg: php56-redis
    opts: "build-from-source"
php56_brew:
  - php56-oauth
  - php56-amqp
  - php56-mongo  
  - php56-mongodb
  - php56-solr
  - php56-ssh2
  - php56-http
  - php56-uuid
  - php56-xdebug
  - php56-yaml
  - php56-v8js
  - php56-memcached
  - blackfire-php56

## Defaults for php70
php70_brew_with_opts:
  - pkg: php70
    opts: "build-from-source"
  - pkg: php70-redis
    opts: "HEAD,build-from-source"
  - pkg: php70-memcached
    opts: "HEAD,build-from-source"
  - pkg: php70-ssh2
    opts: "HEAD,build-from-source"
  - pkg: php70-yaml
    opts: "HEAD,build-from-source"
php70_brew:
  - php70-apcu
  - php70-apcu-bc
  - php70-oauth
  - php70-amqp
  - php70-mongodb
  - php70-ssh2
  - php70-uuid
  - php70-xdebug
  - php70-v8js
  - blackfire-php70
