---
- stat: path=~/.config/nvim
  register: nvim_config_dir
- name: Get repo nvim-gecko
  git:
    repo: https://github.com/luishdez/neovim-gecko.git
    dest: ~/.config/nvim
    accept_hostkey: true
  when: nvim_config_dir.stat.exists
- name: Setup vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim

# @todo chmod 755 to -R with sudo ~/.local/share/nvim
