---
- name: Tap hombrew formulas
  homebrew_tap: name={{ item }}
  with_items: brew_taps

- name: Install homebrew package(s) with brew options
  homebrew: name={{ item.pkg }} install_options={{ item.opts }} state={{ item.state|default("latest") }}
  with_items: "{{ go_brew_with_opts }}"

- name: Install the homebrew packages
  homebrew: name={{ item }} state=latest
  with_items: "{{ go_brew }}"
